version: "3"

# for development purposes only
services:
  test-server:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - ./tests/data:/data/
      - .:/code/
      - ./docker/ports.conf:/etc/apache2/ports.conf
      - ./docker/sync-api.conf:/etc/apache2/sites-available/sync-api.conf
