SET KEBOOLA_STACK=runner-sync-api-test
SET KEBOOLA_STACK_REGION=us-east-1
SET AWS_ACCESS_KEY_ID=AKIAIEBKSHXORYJWUDXQ
SET AWS_SECRET_ACCESS_KEY=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
SET KBC_TEST_TOKEN=6267-159502-LwcxB0R71NxiNrZrX9mywCYFrEqQgS8CkCzyWQ0v
SET KBC_TEST_URL=https://connection.keboola.com/

KEBOOLA_STACK=runner-sync-api-test
KEBOOLA_STACK_REGION=us-east-1
AWS_ACCESS_KEY_ID=AKIAIEBKSHXORYJWUDXQ
AWS_SECRET_ACCESS_KEY=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
KBC_TEST_TOKEN=6267-159502-LwcxB0R71NxiNrZrX9mywCYFrEqQgS8CkCzyWQ0v
KBC_TEST_URL=https://connection.keboola.com/
